name: Deploy Foam website

on:
  push:

jobs:
  deploy-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1

      - name: Install website dependencies
        run: npm install
        working-directory: _layouts
      - name: Build website
        run: npm run build -- --prefix-paths
        working-directory: _layouts

      - name: Deploy to the gh-pages branch
        # only deploy when the main branch has some changes
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_layouts/public
          
      - name: Slack Message
        # You may pin to the exact commit or the version.
        # uses: someimportantcompany/github-actions-slack-message@0b470c14b39da4260ed9e3f9a4f1298a74ccdefd
        uses: someimportantcompany/github-actions-slack-message@v1
        with:
          # Text to send to Slack, in Slack's "mrkdwn" format - required.
          text: "deploy done!!"
          # The colour of the Slack attachment.
          # color: # optional
          # A Slack bot token to send messages with - required if `webhook-url` was not provided.
          #bot-token: # optional
          # A Slack webhook URL to send messages to - required if `bot-token` was not provided.
          #webhook-url: # optional
          # The Slack channel - required if `bot-token` was provided.
          channel: github
          # The ID of the existing Slack message to update - only valid if `bot-token` was provided.
          #message-id: # optional
